name: Main PR actions

on:
  pull_request:
    branches: main

jobs:
  pr_actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: [12.x, 14.x, 16.x]
      - run: yarn install
      - run: yarn start
